version: "3"

services:
  # frontenda v razvojni fazi ne potrebujemo v dockerju
  # ohranjamo za teste
  frontend:
    image: bizjak3/tpo:frontend
    hostname: bizjak3/tpo:frontend
    ports:
    - "10010:80"

  # backenda v razvojni fazi ne potrebujemo v dockerju
  # ohranjamo za teste
  #backend:
  #  build: backend
  #  ports:
  #  - "10011:80"


  # databases
  mariadb:
    image: mariadb
    hostname: mariadb
    restart: on-failure
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PasjehodecDB
      MYSQL_USER: pasjehodec
      MYSQL_PASSWORD: pasjehodec
    ports:
    - "10001:3306"
  redis:
    image: redis
    hostname: redis
    restart: on-failure
    volumes:
      - ./volumes/redis:/data
    ports:
    - "10002:6379"

  watchtower:
    image: v2tec/watchtower
    environment:
      REPO_USER: bizjak3
      REPO_PASS: Vp&LLPQJdES6RXc
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --debug